/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "back_button": { "initialHeight": 30, "initialWidth": 50, "leftImageWidth": 16, "rightImageWidth": 5, "text": "Back", "view": "DC.PushButton" },
    "browser": { "clearSelectionOnBack": true, "view": "DC.Browser" },
    "detailDescription": { "propertyValues": { "textBinding": { "keypath": "list.selection.description" } }, "text": "Description", "view": "DC.Text" },
    "detailSubtitle": { "propertyValues": { "textBinding": { "keypath": "list.selection.official_title" } }, "text": "Location", "view": "DC.Text" },
    "detailSubtitle1": { "propertyValues": { "textBinding": { "keypath": "list.selection.department" } }, "text": "Location", "view": "DC.Text" },
    "detailSubtitle2": { "propertyValues": { "textBinding": { "keypath": "list.selection.years" } }, "text": "Location", "view": "DC.Text" },
    "detailSubtitle3": { "propertyValues": { "textBinding": { "keypath": "list.selection.career" } }, "view": "DC.Text" },
    "detailSubtitle4": { "propertyValues": { "textBinding": { "keypath": "list.selection.edu" } }, "text": "Location", "view": "DC.Text" },
    "detailTitle": { "propertyValues": { "textBinding": { "keypath": "list.selection.Name" } }, "text": "Title", "view": "DC.Text" },
    "header": { "rootTitle": "U.S.A. Cabinet", "view": "DC.Header" },
    "image": { "propertyValues": { "srcBinding": { "keypath": "*.image.$href" } }, "view": "DC.ImageLayout" },
    "image1": { "view": "DC.ImageLayout" },
    "list": { "allowsEmptySelection": true, "labelElementId": "rowTitle", "listStyle": "DC.List.EDGE_TO_EDGE", "propertyValues": { "dataArrayBinding": { "keypath": "dataSource.content.item" } }, "sampleRows": 8, "selectionEnabled": true, "useDataSource": true, "view": "DC.List" },
    "rowTitle": { "propertyValues": { "textBinding": { "keypath": "*.Name" } }, "text": "Item", "view": "DC.Text" },
    "stackLayout": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "text": { "propertyValues": { "textBinding": { "keypath": "*.Position" } }, "text": "Text", "view": "DC.Text" },
    "text1": { "text": "Official Title:", "view": "DC.Text" },
    "text2": { "text": "Department:", "view": "DC.Text" },
    "text3": { "text": "Years:", "view": "DC.Text" },
    "text4": { "text": "Career:", "view": "DC.Text" },
    "text5": { "text": "Education:", "view": "DC.Text" }
};






